uspd: Multiple fixes
- Uci Schema updated
- Ubus schema updated
- Config option for sock path
- config option for transaction_timeout
- config option to disable uspd
- Align with latest bbf
- Added tests

diff --git a/uspd/files/uspd.init b/uspd/files/uspd.init
--- a/uspd/files/uspd.init
+++ b/uspd/files/uspd.init
@@ -6,9 +6,48 @@ STOP=10
 USE_PROCD=1
 PROG=/usr/sbin/uspd
 
+validate_uspd_usp_section()
+{
+	uci_validate_section uspd uspd "usp" \
+		'enabled:bool:true' \
+		'granularitylevel:uinteger' \
+		'debug:bool:false' \
+		'loglevel:uinteger' \
+		'sock:string' \
+		'transaction_timeout:string'
+}
+
+configure_uspd()
+{
+	local enabled debug sock transaction_timeout
+
+	config_load uspd
+
+	validate_uspd_usp_section || {
+		log "Validation of usp section failed"
+		return 1;
+	}
+
+	[ ${enabled} -eq 0 ] && exit 0
+
+	if [ ${debug} -eq 1 ]; then
+		procd_set_param stdout 1
+		procd_set_param stderr 1
+	fi
+
+	if [ -n "${sock}" ]; then
+		procd_append_param command -s ${sock}
+	fi
+
+	if [ -n "${transaction_timeout}" ]; then
+		procd_append_param command -t ${transaction_timeout}
+	fi
+}
+
 start_service() {
-	procd_open_instance
+	procd_open_instance usp
 	procd_set_param command ${PROG}
+	configure_uspd
 	procd_set_param respawn
 	procd_close_instance
 }
