owsd: update to new version with multiple ports
Signed-off-by: Denis Osvald <denis.osvald@sartura.hr>

diff --git a/owsd/files/owsd.init b/owsd/files/owsd.init
--- a/owsd/files/owsd.init
+++ b/owsd/files/owsd.init
@@ -8,18 +8,38 @@ PROG=/usr/bin/owsd
 CONFIGFILE="/etc/config/owsd"
 
 validate_owsd() {
-	uci_validate_section owsd config setup \
+	uci_validate_section "owsd" "owsd" "global" \
 		'sock:string' \
-		'port:integer' \
-		'origin:list(string)' \
-		'cert:string' \
-		'key:string' \
-		'www:string' \
-
+		'www:string'
 }
 
 append_origin() {
 	procd_append_param command -o "$1"
+}
+
+validate_owsd_iface() {
+	uci_validate_section "owsd" "owsd-listen" "$1" \
+		'port:port' \
+		'interface:string' \
+		'origin:list(string)' \
+		'cert:string' \
+		'key:string'
+}
+
+parse_owsd_iface() {
+	local port interface cert key
+
+	validate_owsd_iface "$1" || {
+		echo "Validation failed"
+		return 1
+	}
+
+	[ -n "${port}"      ] && procd_append_param command -p "${port}"
+	[ -n "${interface}" ] && procd_append_param command -i "${interface}"
+	[ -n "${cert}"      ] && procd_append_param command -c "${cert}"
+	[ -n "${key}"       ] && procd_append_param command -k "${key}"
+
+	config_list_foreach "$1" "origin" append_origin
 }
 
 start_service() {
@@ -27,17 +47,17 @@ start_service() {
 	procd_open_instance
 	procd_set_param command $PROG
 
+	local sock www
+
 	validate_owsd || {
-		echo "validation failed"
+		echo "Global validation failed"
 		return 1
 	}
 
-	[ -n "${sock}" ] && procd_append_param command -s "${sock}"
-	[ -n "${port}" ] && procd_append_param command -p "${port}"
-	config_list_foreach "setup" "origin" append_origin
-	[ -n "${cert}" ] && procd_append_param command -c "${cert}"
-	[ -n "${key}" ] && procd_append_param command -k "${key}"
-	[ -n "${www}" ] && procd_append_param command -w "${www}"
+	[ -n "${sock}"      ] && procd_append_param command -s "${sock}"
+	[ -n "${www}"       ] && procd_append_param command -w "${www}"
+
+	config_foreach parse_owsd_iface "owsd-listen"
 
 #	procd_set_param stderr 1
 	procd_set_param respawn
