ieee1905: Configure registrar

diff --git a/ieee1905/files/etc/init.d/ieee1905 b/ieee1905/files/etc/init.d/ieee1905
--- a/ieee1905/files/etc/init.d/ieee1905
+++ b/ieee1905/files/etc/init.d/ieee1905
@@ -11,8 +11,8 @@ INTERFACE=""
 validate_ieee1905_section()
 {
 	uci_validate_section ieee1905 ieee1905 "${1}" \
-		'debug:bool:true' \
-		'enabled:bool:true'
+		'debug:bool:false' \
+		'enabled:bool:false'
 }
 
 get_device_name() {
@@ -46,24 +46,63 @@ validate_al_iface_section()
 {
 	uci_validate_section ieee1905 al-iface "${1}" \
 		'enabled:bool:false' \
-		'ifname:string' \
-		'media:string:eth' \
-		'manufacturer_name:string:iopsys' \
+		'ifname:string:br-lan' \
+		'media:string:bridge' \
+		'manufacturer_name:string' \
 		'model_name:string' \
-		'model_number:string' \
+		'model_number:string:000000' \
 		'device_name:string' \
 		'serial_number:string'
+}
+
+get_ifindex()
+{
+	local ifname=${1}
+	local ifindex=$(cat /sys/class/net/${ifname}/upper_*/ifindex 2>/dev/null)
+	if [ -z ${ifindex} ]; then
+		ifindex=$(cat /sys/class/net/${ifname}/ifindex)
+	fi
+	echo ${ifindex}
+}
+
+get_wlan_passkey()
+{
+	local ifname=${1}
+	local pass=""
+	local count=0
+
+	while true
+	do
+		local devname=$(uci get wireless.@wifi-iface[${count}].ifname 2>/dev/null)
+		if [ $? -ne 0 ]; then
+			break;
+		fi
+		if [ "${devname}"=="${ifname}" ]; then
+			pass=$(uci get wireless.@wifi-iface[${count}].key 2>/dev/null)
+			break;
+		fi
+		count=$((count+1))
+	done
+	echo ${pass}
 }
 
 configure_interface()
 {
 	local ifname media enabled manufacturer_name model_name model_number device_name serial_number
+	local uuid ifindex
+
 	validate_al_iface_section ${1} || {
-		echo "Validation of global section failed"
-		return 1;
+		echo "Validation of al-iface sec failed"
+		exit 1;
 	}
 
 	if [ ${enabled} -eq 0 ]; then
+		return;
+	fi
+
+	# Only continue if interface exists
+	ifconfig ${ifname} 2>/dev/null 1>/dev/null
+	if [ $? -ne 0 ]; then
 		return;
 	fi
 
@@ -73,16 +112,64 @@ configure_interface()
 		INTERFACE="${INTERFACE},${ifname}"
 	fi
 
-	local uuid=$(cat /proc/sys/kernel/random/uuid)
-	local ifindex=$(cat /sys/class/net/${ifname}/ifindex 2>/dev/null)
-	#local ifindex=$(cat /sys/class/net/${ifname}/upper_*/ifindex 2>/dev/null)
-	if [ -z ${ifindex} ]; then
-		ifindex=$(cat /sys/class/net/${ifname}/ifindex)
+	if [ -z ${manufacturer_name} ]; then
+		manufacturer_name=$(db get hw.board.iopVerCustomer)
 	fi
+
+	if [ -z ${model_name} ]; then
+		model_name=$(db get hw.board.model_name)
+	fi
+
+	if [ -z ${device_name} ]; then
+		device_name=$(db get hw.board.model_name)
+	fi
+
+	if [ -z ${serial_number} ]; then
+		serial_number=$(db get hw.board.serial_number)
+	fi
+
+	if [ "${media}"=="bridge" ]; then
+		echo "Get interfaces from bridge"
+		local lower=$(ls -1 /sys/class/net/${ifname}/|grep lower_|tr '_' ' '|awk '{printf $2" "}')
+		for intf in ${lower}
+		do
+			ubus list wifi.ap.${intf} 2>/dev/null 1>/dev/null
+			if [ $? -eq 0 ]; then
+				INTERFACE="${INTERFACE},${intf}"
+				uuid=$(cat /proc/sys/kernel/random/uuid)
+				ifindex=$(get_ifindex ${intf})
+				local key=$(get_wlan_passkey ${ifname})
+				json_add_object
+				json_add_string ifname ${intf}
+				json_add_string media "wifi"
+				json_add_string network_key ${key}
+				json_add_string manufacturer_name ${manufacturer_name}
+				json_add_string model_name ${model_name}
+				json_add_string model_number ${model_number}
+				json_add_string device_name ${device_name}
+				json_add_string serial_number ${serial_number}
+				json_add_string uuid ${uuid}
+				json_add_int ifindex ${ifindex}
+				json_close_object
+			fi
+		done
+	fi
+	uuid=$(cat /proc/sys/kernel/random/uuid)
+	ifindex=$(get_ifindex ${ifname})
 
 	json_add_object
 	json_add_string ifname ${ifname}
-	json_add_string media ${media}
+
+	if [ "${media}"=="bridge" ]; then
+		json_add_string media "eth"
+	elif [ "${media}"=="wifi" ]; then
+		local key=$(get_wlan_passkey ${ifname})
+		json_add_string media "wifi"
+		json_add_string network_key ${key}
+	else
+		json_add_string media ${media}
+	fi
+
 	json_add_string manufacturer_name ${manufacturer_name}
 	json_add_string model_name ${model_name}
 	json_add_string model_number ${model_number}
@@ -99,7 +186,7 @@ validate_al_section()
 		'enabled:bool:false' \
 		'basemacint:string:wan' \
 		'almac:string' \
-		'registrar:string' \
+		'registrar:bool:false' \
 		'mapall:bool:true' \
 		'debug_level:uinteger:1' \
 		'alme_port:port:8888' \
@@ -115,8 +202,8 @@ configure_al_entity()
 	local registrar cmdu_event discovery_timer map_plugin
 
 	validate_al_section ${1} || {
-		echo "Validation of global section failed"
-		return 1;
+		echo "Validation of al section failed"
+		exit 1;
 	}
 
 	if [ -z ${almac} ]; then
@@ -130,7 +217,14 @@ configure_al_entity()
 	fname=$(db get hw.board.boardId)
 	cname=$(db get hw.board.iopVerCustomer)
 	model=$(db get hw.board.routerModel)
-	cUrl="http://192.168.1.1"
+	# get ip from lan bridge first
+	cUrl=$(ifconfig br-lan 2>/dev/null|grep "inet addr:"|tr ':' ' '|awk '{printf $3}')
+	if [ -z ${cUrl} ]; then
+		cUrl=$(ifconfig br-wan 2>/dev/null|grep "inet addr:"|tr ':' ' '|awk '{printf $3}')
+	fi
+	if [ -z ${cUrl} ]; then
+		cUrl="http://192.168.1.1"
+	fi
 
 	json_init
 	# fill the al-iface info
@@ -150,7 +244,7 @@ configure_al_entity()
 	json_add_string mac ${basemac}
 	json_add_string interfaces ${INTERFACE}
 	json_add_int map ${mapall}
-	json_add_string registrar ${registrar}
+	json_add_int registrar ${registrar}
 	json_add_int debug_level ${debug_level}
 	json_add_int alme_port ${alme_port}
 	json_add_int cmdu_event ${cmdu_event}
@@ -159,7 +253,7 @@ configure_al_entity()
 	json_close_object
 
 	json_dump >${AL_CONF}
-
+	sync
 }
 
 configure_ieee1905()
@@ -201,7 +295,7 @@ start_service() {
 	procd_open_instance ieee1905
 	procd_set_param command ${PROG}
 	configure_network
-	procd_set_param respawn
+	# procd_set_param respawn
 	procd_close_instance
 }
 
@@ -212,5 +306,6 @@ reload_service() {
 
 service_triggers() {
 	procd_add_reload_trigger "network"
+	procd_add_reload_trigger "wireless"
 	procd_add_reload_trigger "netmode"
 }
