obuspa: Rebase with v2.0.0
Description:
 - Rebase with obuspa v2.0.0
 - Added more configurable options in obuspa uci
 - Optimized default db generation from uci
 - moved interface from connection to global obuspa context in uci

diff --git a/obuspa/files/etc/init.d/obuspa b/obuspa/files/etc/init.d/obuspa
--- a/obuspa/files/etc/init.d/obuspa
+++ b/obuspa/files/etc/init.d/obuspa
@@ -5,107 +5,215 @@ USE_PROCD=1
 
 PROG=/usr/sbin/obuspa
 l3device=""
-
-CTRL_PATH="Device.LocalAgent.Controller.1."
-MTP_PATH="Device.LocalAgent.MTP.1."
-CONN_PATH="Device.STOMP.Connection.1."
+certificate=""
+PARAM_FILE="/tmp/obuspa_param_reset.txt"
+conn_num=1
+mtp_num=1
+stomp_num=1
 
 log() {
 	echo "${@}"|logger -t obuspa -p debug
 }
 
 db_set() {
-	log "DBSET param|${1}| value|${2}|"
-	${PROG} -c dbset ${1} ${2}
+	if [ -n "${1}" ]; then
+		echo "${1} \"${2}\"">>${PARAM_FILE}
+	else
+		echo >>${PARAM_FILE}
+	fi
+}
+
+validate_obuspa_section()
+{
+	uci_validate_section obuspa obuspa "${1}" \
+		'cert:string:"/etc/obuspa/rootCA.pem"' \
+		'interface:string:wan' \
+		'debug:bool:false'
 }
 
 validate_controller_section()
 {
 	uci_validate_section obuspa controller "${1}" \
-		'endpointid:string:"self:usp-controller.com"'
+		'endpointid:string:"self:usp-controller.com"' \
+		'enable:bool:true' \
+		'AssignedRole:uinteger:1' \
+		'PeriodicNotifInterval:uinteger:86400' \
+		'PeriodicNotifTime:string:"0001-01-01T00:00:00Z"' \
+		'USPRetryMinimumWaitInterval:uinteger:5' \
+		'USPRetryIntervalMultiplier:uinteger:2000' \
+		'ControllerCode:string' \
+		'protocol:or("STOMP","CoAP")' \
+		'CoAPHost:string' \
+		'CoAPPath:string' \
+		'CoAPPort:uinteger'
 }
 
 validate_mtp_section()
 {
 	uci_validate_section obuspa mtp "${1}" \
 		'enable:bool:true' \
-		'protocol:string:"STOMP"' \
-		'destination:string:'
+		'protocol:or("STOMP","CoAP")' \
+		'destination:string' \
+		'CoAPPath:string' \
+		'CoAPPort:uinteger'
 }
 
 validate_connection_section()
 {
 	uci_validate_section obuspa connection "${1}" \
 		'host:string:"usp-controller.com"' \
-		'username:string:username' \
-		'password:string:password' \
+		'username:string:""' \
+		'password:string:""' \
 		'encryption:bool:true' \
-		'interface:string:wan'
+		'enable:bool:true' \
+		'port:uinteger:61613' \
+		'virtualhost:string:"/"' \
+		'EnableHeartbeats:bool:true' \
+		'OutgoingHeartbeat:uinteger:30000' \
+		'IncomingHeartbeat:uinteger:300000' \
+		'ServerRetryInitialInterval:uinteger:60' \
+		'ServerRetryIntervalMultiplier:uinteger:2000' \
+		'ServerRetryMaxInterval:uinteger:30720'
 }
 
 configure_controller() {
-	local endpointid
+	local endpointid enable AssignedRole PeriodicNotifInterval PeriodicNotifTime USPRetryMinimumWaitInterval
+	local USPRetryIntervalMultiplier ControllerCode protocol CoAPHost CoAPPath CoAPPort
 
 	validate_controller_section "${1}" || {
 		log "Validation of section failed"
 		return 1;
 	}
-	db_set "${CTRL_PATH}EndpointID" ${endpointid}
+	db_set Device.LocalAgent.Controller.${conn_num}.EndpointID "${endpointid}"
+	db_set Device.LocalAgent.Controller.${conn_num}.Alias "cpe-${conn_num}"
+	db_set Device.LocalAgent.Controller.${conn_num}.Enable "true"
+	db_set Device.LocalAgent.Controller.${conn_num}.AssignedRole "Device.LocalAgent.ControllerTrust.Role.${AssignedRole}"
+	db_set Device.LocalAgent.Controller.${conn_num}.PeriodicNotifInterval "${PeriodicNotifInterval}"
+	db_set Device.LocalAgent.Controller.${conn_num}.PeriodicNotifTime "${PeriodicNotifTime}"
+	db_set Device.LocalAgent.Controller.${conn_num}.USPRetryMinimumWaitInterval "${USPRetryMinimumWaitInterval}"
+	db_set Device.LocalAgent.Controller.${conn_num}.USPRetryIntervalMultiplier "${USPRetryIntervalMultiplier}"
+	db_set Device.LocalAgent.Controller.${conn_num}.ControllerCode "${ControllerCode}"
+	db_set Device.LocalAgent.Controller.${conn_num}.MTP.${conn_num}.Alias "cpe-${conn_num}" 
+	db_set Device.LocalAgent.Controller.${conn_num}.MTP.${conn_num}.Enable "${enable}"
+	db_set Device.LocalAgent.Controller.${conn_num}.MTP.${conn_num}.Protocol "${protocol}"
+	if [ "${protocol}"=="STOMP" ]; then
+		db_set Device.LocalAgent.Controller.${conn_num}.MTP.${conn_num}.STOMP.Reference "Device.STOMP.Connection.${conn_num}"
+		db_set Device.LocalAgent.Controller.${conn_num}.MTP.${conn_num}.STOMP.Destination "controller-notify-dest"
+	elif [ "${protocol}"=="CoAP" ]; then
+		db_set Device.LocalAgent.Controller.${conn_num}.MTP.${conn_num}.CoAP.Host "${CoAPHost}"
+		db_set Device.LocalAgent.Controller.${conn_num}.MTP.${conn_num}.CoAP.Path "${CoAPPath}"
+		db_set Device.LocalAgent.Controller.${conn_num}.MTP.${conn_num}.CoAP.Port "${CoAPPort}"
+	else
+		log "Unsupported protocol ${protocol}"
+	fi
+	db_set
+	conn_num=$((conn_num+1))
 }
 
 configure_mtp() {
-	local protocol enable destination
+	local protocol enable destination CoAPPath CoAPPort
 
 	validate_mtp_section "${1}" || {
 		log "Validation of section failed"
 		return 1;
 	}
-	db_set "${MTP_PATH}Enable" ${enable}
-	db_set "${MTP_PATH}Protocol" ${protocol}
-	db_set "${MTP_PATH}STOMP.Destination" ${destination}
+	db_set Device.LocalAgent.MTP.${mtp_num}.Alias "cpe-${mtp_num}"
+	db_set Device.LocalAgent.MTP.${mtp_num}.Enable "${enable}"
+	db_set Device.LocalAgent.MTP.${mtp_num}.Protocol "${protocol}"
+	if [ "${protocol}"=="STOMP" ]; then
+		db_set Device.LocalAgent.MTP.${mtp_num}.STOMP.Reference "Device.STOMP.Connection.${mtp_num}"
+		db_set Device.LocalAgent.MTP.${mtp_num}.STOMP.Destination "${destination}"
+	elif [ "${protocol}"=="CoAP" ]; then
+		db_set Device.LocalAgent.MTP.${mtp_num}.CoAP.Path "${CoAPPath}"
+		db_set Device.LocalAgent.MTP.${mtp_num}.CoAP.Port "${CoAPPort}"
+	else
+		log "Unsupported protocol ${protocol}"
+	fi
+	db_set
+	mtp_num=$((mtp_num+1))
 }
 
 configure_connection() {
-	local host username password encryption interface
+	local host username password encryption enable port virtualhost EnableHeartbeats
+	local OutgoingHeartbeat IncomingHeartbeat ServerRetryInitialInterval
+	local ServerRetryIntervalMultiplier ServerRetryMaxInterval
 
 	validate_connection_section "${1}" || {
 		log "Validation of section failed"
 		return 1;
 	}
 
+	db_set Device.STOMP.Connection.${stomp_num}.Host "${host}"
+	db_set Device.STOMP.Connection.${stomp_num}.Username "${username}"
+	db_set Device.STOMP.Connection.${stomp_num}.Password "${password}"
+
+	db_set Device.STOMP.Connection.${stomp_num}.Alias "cpe-${stomp_num}"
+	db_set Device.STOMP.Connection.${stomp_num}.Enable "${enable}"
+	db_set Device.STOMP.Connection.${stomp_num}.Port "${port}"
+	db_set Device.STOMP.Connection.${stomp_num}.X_ARRIS-COM_EnableEncryption "${encryption}"
+	db_set Device.STOMP.Connection.${stomp_num}.VirtualHost "${virtualhost}"
+	db_set Device.STOMP.Connection.${stomp_num}.EnableHeartbeats "${EnableHeartbeats}"
+	db_set Device.STOMP.Connection.${stomp_num}.OutgoingHeartbeat "${OutgoingHeartbeat}"
+	db_set Device.STOMP.Connection.${stomp_num}.IncomingHeartbeat "${IncomingHeartbeat}"
+	db_set Device.STOMP.Connection.${stomp_num}.ServerRetryInitialInterval "${ServerRetryInitialInterval}"
+	db_set Device.STOMP.Connection.${stomp_num}.ServerRetryIntervalMultiplier "${ServerRetryIntervalMultiplier}"
+	db_set Device.STOMP.Connection.${stomp_num}.ServerRetryMaxInterval "${ServerRetryMaxInterval}"
+	db_set
+	stomp_num=$((stomp_num+1))
+}
+
+configure_obuspa() {
+	local cert interface debug
+
+	validate_obuspa_section "${1}" || {
+		log "Validation of section failed"
+		return 1;
+	}
+
+	if [ ${debug} -eq 1 ]; then
+		# Forward stdout of the command to logd
+		procd_set_param stdout 1
+		# Same for stderr
+		procd_set_param stderr 1
+	fi
+
 	# Get wan L3 interface
-	json_load "$(ubus call network.interface.${interface} status)"
+	json_load "$(ubus -t 2 call network.interface.${interface} status)"
 	json_get_var l3device l3_device
-	echo "l3device ${l3device}">/dev/console
 	export USP_BOARD_IFNAME=${l3device}
 
 	# Set this variable for root user
 	echo "export USP_BOARD_IFNAME=${l3device}">/root/.profile
 
-	db_set "${CONN_PATH}Host" ${host}
-	db_set "${CONN_PATH}Username" ${username}
-	db_set "${CONN_PATH}Password" ${password}
-	db_set "${CONN_PATH}X_ARRIS-COM_EnableEncryption" ${encryption}
-}
+	[ -f $cert ] && certificate=$cert
 
+}
 db_init() {
-	[ -f /tmp/usp.db ] && rm -f /tmp/usp.db
+	[ -f ${PARAM_FILE} ] && rm -f ${PARAM_FILE}
 
 	config_load obuspa
-	config_foreach configure_connection connection
+	config_foreach configure_obuspa obuspa
 	config_foreach configure_controller controller
+	config_foreach configure_connection connection
 	config_foreach configure_mtp mtp
+	db_set Internal.Reboot.Cause "LocalFactoryReset"
 }
+
+boot() {
+	[ -f /tmp/usp.db ] && rm -f /tmp/usp.db
+
+	start
+}
+
 start_service() {
 	db_init
-	procd_open_instance
+	procd_open_instance obuspa
 	procd_set_param env USP_BOARD_IFNAME=${l3device}
-	# Forward stdout of the command to logd
-	# procd_set_param stdout 1
-	# Same for stderr
-	# procd_set_param stderr 1
 	procd_set_param command ${PROG}
-	procd_append_param command -p -v 4
+	procd_append_param command -p -v 4 -r ${PARAM_FILE}
+	if [ -f "${certificate}" ]; then
+		procd_append_param command -t ${certificate}
+	fi
 	procd_set_param respawn
 	procd_close_instance
 }
